### ISSUE TITLE
Scripts will not run. Expecting other dependency "SQLPS" 

### ISSUE THREAD

**Issue by Russweb** [Microsoft/Code-Search#1]
My server was brought to its knees rapidly trying to first setup this feature.
I need to stop the processes in order to first up the resources...but the instructions are not working.

According to this release page, I should be able to easily launch the provided scripts.
https://www.visualstudio.com/en-us/docs/search/administration/#stop-indexing

However, those blow up trying to run:

PS D:\CodeSearchScripts> .\StopSearchIndexing.ps1
Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. Do you want to run D:\CodeSearchScripts\StopSearchIndexing.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R

cmdlet StopSearchIndexing.ps1 at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ServerInstance: myDBServer
ConfigurationDatabaseName: Tfs_Configuration
**_Import-Module : The specified module 'SQLPS' was not loaded because no valid module file was found in any module
directory.
At D:\CodeSearchScripts\StopSearchIndexing.ps1:11 char:1
- Import-Module -Name SQLPS
- ~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ResourceUnavailable: (SQLPS:String) [Import-Module], FileNotFoundException
  - FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Invoke-Sqlcmd : The term 'Invoke-Sqlcmd' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\CodeSearchScripts\StopSearchIndexing.ps1:12 char:1
- Invoke-Sqlcmd -InputFile "StopSearchIndexing.sql" -serverInstance $ServerInstanc ...
- ~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Invoke-Sqlcmd:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException_**

**Comment by JimsonChalissery** [comment]
@Russweb If your SQL server instance is on a separate machine, do run the scripts on that machine. I understand this was not called out in our documentation, and we'll rectify that. If you run into further issues, do drop us a mail at vsosrch@microsoft.com.
