### ISSUE TITLE
collections with spaces in their names make the scripts fail

### ISSUE THREAD

**Issue by Laibalion** [Microsoft/Code-Search#16]
In case a collection has a space character in its name, the scripts won't work since it doesn't properly put quotes around the string parameters

**Comment by bittusarkar** [comment]
Closing this issue as it is too old. We have fixed a lot of bugs since then. Please let us know if this still reproduces and in which script.

**Comment by Laibalion** [comment]
It's still relevant, and all of the scripts that need collection names or names of their database files (which by default are name as tfs_'collection name'.

**Comment by bittusarkar** [comment]
@Laibalion It would help if you can provide some concrete reproduction steps.
