### ISSUE TITLE
Unable to disable indexing of specific projects

### ISSUE THREAD

**Issue by peder** [Microsoft/Code-Search#18]
Is there a way to disable indexing specific projects? I've poked around the `Search` schema in the database, and I was curious if I could mark a project as `IsDeleted` in the `tbl_ClassificationNode` table or if there's another method I should try.

**Comment by bittusarkar** [comment]
Disabling indexing at a project level is not supported. You can file a feature request for this at [https://developercommunity.visualstudio.com/content/idea/post.html?space=22]().
