### ISSUE TITLE
Script is referencing the undefined variable $configLogDir

### ISSUE THREAD

**Issue by sqdavid** [Microsoft/Code-Search#34]
Hi, 
problem: in ./SearchDiagonistics/CollectionDBSearchDiagnostics.ps1, _$configLogDir_ is used instead of _$collectionLogDir_ 

[https://github.com/Microsoft/Code-Search/blob/3be409ea44ce2a58e5936f6534b4273b0d5b51e4/SearchDiagonistics/CollectionDBSearchDiagnostics.ps1#L122](https://github.com/Microsoft/Code-Search/blob/3be409ea44ce2a58e5936f6534b4273b0d5b51e4/SearchDiagonistics/CollectionDBSearchDiagnostics.ps1#L122)

It is a simple fix just to replace the variable name.

If you are very busy, i could make the replace.

regards.

**Comment by bittusarkar** [comment]
This was recently fixed. Thank you for reporting!
