### ISSUE TITLE
/SearchDiagonistics/ConfigurationDBSearchDiagnostics.ps1 should require "Tfs collection database" as parameter

### ISSUE THREAD

**Issue by sqdavid** [Microsoft/Code-Search#36]
/SearchDiagonistics/ConfigurationDBSearchDiagnostics.ps1 executes the Sql script "ExtensionData.sql" that queries [tbl_RegistryItems] in the default tfs collection database.
This database may have a different name than the one hardcoded in the script.

My suggestion is to ask the collection database as a parameter for the PS script, having a default with the hardcoded name.

https://github.com/Microsoft/Code-Search/blob/3be409ea44ce2a58e5936f6534b4273b0d5b51e4/SearchDiagonistics/ConfigurationDBDiagnosticScripts/ExtensionData.sql#L6

Regards.

**Comment by bittusarkar** [comment]
Thank you for reporting this bug. This file has been deleted now.
