### ISSUE TITLE
TFS 2018.2 Wiki reindex

### ISSUE THREAD

**Issue by Archeotype** [Microsoft/Code-Search#39]
Hi,
I had to reindex search indexes, code and workitem are working well, but wiki search is still in state "We are not able to show results because one or more projects in your collection are still being indexed" and cannot be restored. 2018RTW does not support wiki reindex and I'm no able to understand/write that script.
Thanks.

**Comment by Archeotype** [comment]
I made it working using 'Microsoft.VisualStudio.Services.Search.Server.Jobs.WikiAccountFaultInJob but there also problem typ_JobScheduleTable vs typ_JobScheduleTable2 datatype.

**Comment by bittusarkar** [comment]
Closing because the issue seems to be resolved.
