### ISSUE TITLE
The disk space is running out and the search not work

### ISSUE THREAD

**Issue by shayki5** [Microsoft/Code-Search#41]
Hi,
We have very big TFS DB (about 1.6TB).
We have separate code server with disk space of 600GB, after few weeks the space is running out and the search not working.
How we can make a retention policy to delete data and clean up the space?
(For example - every 2 weeks 200GB will be deleted).
By the way, we have TFS 2017.3.
Thank you!

**Comment by bittusarkar** [comment]
I am afraid there is no provision for data clean-up as that will result in missing search results. If you do not want code search on a collection, you can uninstall the code search extension for it. But if you are talking about logs eating up disk space, we can talk more. I am closing this issue right now.
